import {decrypt} from './security.mjs';
export class HttpError extends Error {constructor(message,status=400){super(message);this.status=status}}
export const configured=()=>!!(process.env.SUPABASE_URL&&process.env.SUPABASE_ANON_KEY&&process.env.SUPABASE_SERVICE_ROLE_KEY);
export function need(value,name){if(!value)throw new HttpError(`${name} 설정이 필요합니다.`,503);return value}
export async function user(req){need(configured(),'데이터베이스');const token=req.headers.get('authorization');if(!token?.startsWith('Bearer '))throw new HttpError('로그인이 필요합니다.',401);const r=await fetch(`${process.env.SUPABASE_URL}/auth/v1/user`,{headers:{apikey:process.env.SUPABASE_ANON_KEY,Authorization:token},cache:'no-store'});if(!r.ok)throw new HttpError('로그인이 만료되었습니다. 다시 로그인해 주세요.',401);return r.json()}
export async function db(table,query='',method='GET',body){need(configured(),'데이터베이스');const r=await fetch(`${process.env.SUPABASE_URL}/rest/v1/${table}?${query}`,{method,headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`,'Content-Type':'application/json',Prefer:'return=representation'},body:body?JSON.stringify(body):undefined,cache:'no-store'});if(!r.ok)throw new HttpError('데이터 저장/조회에 실패했습니다. DB 연결과 스키마를 확인해 주세요.',502);return r.status===204?[]:r.json()}
export function uuid(v){if(!/^[0-9a-f-]{36}$/i.test(v||''))throw new HttpError('잘못된 항목입니다.');return v}
export async function owned(table,id,owner){const rows=await db(table,`id=eq.${uuid(id)}&owner_id=eq.${owner}`);if(!rows[0])throw new HttpError('항목을 찾을 수 없습니다.',404);return rows[0]}
export async function account(client,owner){const a=(await db('social_accounts',`client_id=eq.${uuid(client)}&owner_id=eq.${owner}&platform=eq.instagram`))[0];if(!a?.token_encrypted)throw new HttpError('먼저 Instagram 계정을 연결해 주세요.',409);if(new Date(a.token_expires_at)<new Date())throw new HttpError('Instagram 인증이 만료되었습니다. 다시 연결해 주세요.',409);return a}
export async function graph(a,path,method='GET',body){const ver=need(process.env.META_GRAPH_VERSION,'Meta API 버전');if(!/^v\d+\.\d+$/.test(ver))throw new HttpError('Meta API 버전을 확인해 주세요.',503);const r=await fetch(`https://graph.instagram.com/${ver}/${path}`,{method,headers:{Authorization:`Bearer ${decrypt(a.token_encrypted)}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(25000)});const data=await r.json();if(!r.ok||data.error)throw new HttpError('Instagram 요청이 실패했습니다. 권한, 계정 연결 및 Meta 앱 설정을 확인해 주세요.',502);return data}
export const textValue=(v,max=5000)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw new HttpError(`내용을 1~${max}자 이내로 입력해 주세요.`);return v.trim()};
